import unittest
import sure

from domidooweb.models import Tag

class ModelTests(unittest.TestCase):
    def test_tag_has_a_unique_autogenerated_id(self):
        tag1 = Tag("foo")
        tag2 = Tag("bar")
        tag1.id.shouldnt.be.equal(tag2.id)
