"""tags

Revision ID: 3591b9451e7d
Revises: 52b66e952d5f
Create Date: 2014-03-07 18:22:52.427286

"""

# revision identifiers, used by Alembic.
revision = '3591b9451e7d'
down_revision = '52b66e952d5f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('places_tags',
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('places_tags')
    op.drop_table('tags')
    ### end Alembic commands ###
